{% set name = "stackvana" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "2020.24w" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win or py != 37]
  merge_build_host: True

requirements:
  host:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stackvana-afw =={{ version }}
    - cfitsio
    - curl
    - fftw
    - gsl
    - hdf5
    - hdf5 * mpi_mpich_*
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - mpich
    - numpy 1.16.*
  run:
    - python
    - stackvana-afw =={{ version }}
    - cfitsio
    - curl
    - fftw
    - gsl
    - hdf5
    - hdf5 * mpi_mpich_*
    - mpich
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - eups

about:
  home: https://github.com/beckermr/stackvana
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'a conda-based LSST DM stack installation'

extra:
  recipe-maintainers:
    - beckermr
