{% set name = "stackvana" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '2018.50w'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
# Note the exta micro version in order to match the tags in the DM eups system.
{% set version = "2019.40w" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win or py < 37 or linux]

requirements:
  run:
    - python
    - pip
    # - stackvana-impl =={{ version }}  # [linux]
    - stackvana-core =={{ version }}

test:
  imports:
    - eups
  commands:
    # is eups around?
    - eups -h
    # make sure env is activated
    - if [[ ! $STACKVANA_ACTIVATED ]]; then exit 1; fi
    - if [[ ! $LSST_HOME ]]; then exit 1; fi
    - if [[ ! $LSST_CONDA_ENV_NAME ]]; then exit 1; fi

about:
  home: https://github.com/beckermr/stackvana
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'a conda-based LSST DM stack installation'

extra:
  recipe-maintainers:
    - beckermr
